name: build-libbarretenberg

on:
  workflow_dispatch:
    inputs:
      noir-ref:
        description: The noir reference to checkout
        required: false
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC
  push:

jobs:
  build-barretenberg:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-22.11
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v12
        with:
          name: barretenberg
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      # Upload does not work with symlinks, using this workaround:
      # https://github.com/actions/upload-artifact/issues/92#issuecomment-1080347032    
      - name: Build barretenberg as libbarretenberg-wasm32
        run: |
          nix build "git+https://github.com/AztecProtocol/barretenberg#wasm32"
          echo "ARTIFACT_UPLOAD_PATH=$(readlink -f result)" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: libbarretenberg-wasm32
          path: ${{ env.ARTIFACT_UPLOAD_PATH }}
          retention-days: 3

