# such target does not exist, name choosen for convention only
name: build-x86_64-pc-windows-wasm
# <arch>-<vendor>-<os>-<env>
# on: 
#   workflow_run:
#     workflows:
#       - libbarretenberg
#     branches:
#       - master
#     types:
#       - completed

on:
  workflow_dispatch:
    inputs:
      noir-ref:
        description: The noir reference to checkout
        required: false
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC
  push:

jobs:
  build-barretenberg:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-22.11
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v12
        with:
          name: barretenberg
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      # Upload does not work with symlinks, using this workaround:
      # https://github.com/actions/upload-artifact/issues/92#issuecomment-1080347032    
      - name: Build barretenberg as libbarretenberg-wasm32
        run: |
          nix build "git+https://github.com/AztecProtocol/barretenberg#wasm32"
          echo "ARTIFACT_UPLOAD_PATH=$(readlink -f result)" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: libbarretenberg-wasm32
          path: ${{ env.ARTIFACT_UPLOAD_PATH }}
          retention-days: 3

  build-x86_64-pc-windows-msvc:
    runs-on: windows-2022
    needs: build-barretenberg
    strategy:
      matrix:
        target: [x86_64-pc-windows-msvc]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Noir repo
        uses: actions/checkout@v3
        with:
          repository: noir-lang/noir
          path: noir
          ref: ${{ inputs.noir-ref || 'master' }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Download pre-built libbarretenberg-wasm32
        id: libbarretenberg-download
        uses: actions/download-artifact@v3
        with:
          name: libbarretenberg-wasm32
          path: libbarretenberg-wasm32

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@1.66.0
        with:
          targets: ${{ matrix.target }}

      - name: Build environment and Compile
        working-directory: noir
        env:
          BARRETENBERG_BIN_DIR: ${{steps.libbarretenberg-download.outputs.download-path}}
        run: |
          cargo build --package nargo_cli --release --target ${{ matrix.target }} --no-default-features --features plonk_bn254_wasm

      - name: Package artifacts
        working-directory: noir
        run: |
          mkdir dist
          cp ./target/${{ matrix.target }}/release/nargo.exe ./dist/nargo.exe
          7z a -tzip nargo-${{ matrix.target }}.zip ./dist/*

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nargo-${{ matrix.target }}
          path: ./noir/dist/*
          retention-days: 3

      - name: Test built artifact
        shell: powershell
        run: |
          cp ./noir/target/${{ matrix.target }}/release/nargo.exe ~/.cargo/bin/

          npm install
          npm test

      - name: Upload binaries to Noir Repo
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        with:
          repo_name: noir-lang/noir
          repo_token: ${{ secrets.NOIR_REPO_TOKEN }}
          file: ./noir/nargo-${{ matrix.target }}.zip
          asset_name: nargo-${{ matrix.target }}.zip
          overwrite: true
          tag: ${{ inputs.noir-ref || 'nightly' }} # This will fail if noir-ref is not a tag (e.g. testing a branch)
      
      # If we're performing a nightly build and it fails acceptance tests then raise an issue.
      - name: Alert on nightly build failure
        uses: JasonEtco/create-an-issue@v2
        if: ${{ failure() && github.event_name == 'schedule' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_NAME: ${{ github.workflow }}
          WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          update_existing: true
          filename: .github/NIGHTLY_BUILD_FAILURE.md
